CREATE TABLE Author (
    id VARCHAR(36)  PRIMARY KEY NOT NULL,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
    description MEDIUMTEXT NOT NULL
);